env:
  es6: true
  node: true
extends: 'eslint:recommended'
parserOptions:
  ecmaVersion: latest
  sourceType: module
ignorePatterns:
  - "special-fields.utils.js"
rules:
  camelcase: error
  indent:
    - error
    - "tab"
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
