swagger: '2.0'
info:
  version: '1'
  title: NoSchema API
host: 'localhost:20077'
basePath: /Adam/noSchema
schemes:
  - http
consumes:
  - application/json
  - multipart/form-data
produces:
  - application/json
  - text/plain
paths:
  /:
    x-swagger-router-controller: controller
    get:
      description: Retrieve a list of 'NoSchema'
      operationId: v1_srvc5443List
      parameters:
        - name: page
          in: query
          type: integer
          description: Page number of the request
        - name: count
          in: query
          type: integer
          description: Number of records per page
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: filter
          in: query
          type: string
          description: Filter records based on certain fields
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: sort
          in: query
          type: string
          description: sort parameter
        - &ref_3
          name: expand
          in: query
          type: boolean
          description: expand document based on relations
          default: false
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
    post:
      description: Create a new 'NoSchema'
      operationId: v1_srvc5443Create
      parameters:
        - name: data
          in: body
          description: Payload to create a 'NoSchema'
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: expireAt
          in: query
          type: string
          description: ISO format date after which the document will get deleted
        - name: expireAfter
          in: query
          type: string
          description: Time after which the document will get deleted.
        - name: upsert
          in: query
          type: boolean
          description: upsert parameter
      responses:
        '200':
          description: List of the entites created
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/simulate:
    x-swagger-router-controller: controller
    post:
      description: validate 'NoSchema'
      operationId: v1_srvc5443Simulate
      parameters:
        - name: data
          in: body
          description: Payload to validate 'NoSchema'
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: generateId
          in: query
          type: boolean
          description: Generate Id for the document
          default: false
        - name: operation
          in: query
          type: string
          description: request method
          default: false
        - name: docId
          in: query
          type: string
          description: request method
          default: false
        - name: select
          in: query
          type: string
          description: select in case of get
          default: false
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/bulkShow:
    x-swagger-router-controller: controller
    get:
      description: Retrieve a list of 'NoSchema'
      operationId: v1_srvc5443BulkShow
      parameters:
        - name: id
          in: query
          type: string
          description: comma separated ids
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: sort
          in: query
          type: string
          description: sort parameter
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/securedFields:
    x-swagger-router-controller: controller
    get:
      description: Retrieve a list of secured fields in 'NoSchema'
      operationId: undefined
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/hook:
    x-swagger-router-controller: controller
    post:
      description: triggers the hook with data
      operationId: v1_srvc5443Hook
      parameters:
        - name: url
          in: query
          type: string
          description: Url to hit
        - name: data
          in: body
          schema:
            type: object
          description: data
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/experienceHook:
    x-swagger-router-controller: controller
    post:
      description: triggers the hook with data
      operationId: v1_srvc5443ExperienceHook
      parameters:
        - name: name
          in: query
          type: string
          description: name of hook to hit
        - name: data
          in: body
          schema:
            type: object
          description: data
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/bulkDelete:
    x-swagger-router-controller: controller
    delete:
      description: Deletes a list of 'noSchema'
      operationId: v1_srvc5443BulkDelete
      parameters:
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: ids
          in: body
          description: Payload to reset a User
          schema:
            type: object
            properties:
              ids:
                type: array
                items:
                  type: string
      responses:
        '200':
          description: Empty Object
        '400':
          description: List document ids not deleted
        '500':
          description: Internal server error
  /utils/count:
    x-swagger-router-controller: controller
    get:
      description: returns count of 'NoSchema'
      operationId: v1_srvc5443Count
      parameters:
        - &ref_0
          name: filter
          in: query
          type: string
          description: Filter records based on certain fields
        - &ref_1
          name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - &ref_2
          name: expand
          in: query
          type: boolean
          description: expand document based on relations
          default: false
      responses:
        '200':
          description: Count of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  '/{id}':
    x-swagger-router-controller: controller
    get:
      description: Retrieve an existing 'NoSchema'
      operationId: v1_srvc5443Show
      parameters:
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: id
          in: path
          type: string
          required: true
          description: Id of the object to be updated
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: expand
          in: query
          type: boolean
          description: expand document based on relations
          default: false
      responses:
        '200':
          description: NoSchema document
        '400':
          description: Bad parameters
        '404':
          description: No records to list with the given parameter set.
        '500':
          description: Internal server error
    put:
      description: Update an existing 'NoSchema'
      operationId: v1_srvc5443Update
      parameters:
        - name: data
          in: body
          description: Payload to update a 'NoSchema'
        - name: id
          in: path
          type: string
          required: true
          description: Id of the 'NoSchema' to be updated
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: expireAt
          in: query
          type: string
          description: ISO format date after which the document will get deleted
        - name: expireAfter
          in: query
          type: string
          description: Time after which the document will get deleted.
        - name: upsert
          in: query
          type: boolean
          description: upsert parameter
      responses:
        '200':
          description: Update entry
        '400':
          description: Bad parameters
        '404':
          description: No records to list with the given parameter set.
        '500':
          description: Internal server error
    delete:
      description: Delete an existing 'NoSchema'
      operationId: v1_srvc5443Destroy
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Id of the 'NoSchema' to be deleted
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
      responses:
        '200':
          description: Empty object
        '400':
          description: Bad parameters
        '404':
          description: No records to list with the given parameter set.
        '500':
          description: Internal server error
  '/utils/export/download/{id}':
    x-swagger-router-controller: controller
    get:
      description: Download the file
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Id of file
        - name: filename
          in: query
          type: string
          description: filename of file
      operationId: v1_srvc5443ExportedFileDownload
      responses:
        '200':
          description: file download
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  '/utils/fileMapper/{fileId}/count':
    x-swagger-router-controller: controller
    get:
      description: returns count of 'NoSchema'
      operationId: fileMapperCount
      parameters:
        - *ref_0
        - *ref_1
        - *ref_2
        - name: fileId
          in: path
          required: true
          type: string
          description: fileId against which we db will be querried
      responses:
        '200':
          description: Count of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/export:
    x-swagger-router-controller: controller
    post:
      description: Retrieve a list of 'NoSchema'
      operationId: v1_srvc5443Export
      parameters:
        - name: filter
          in: body
          type: string
          description: Filter records based on certain fields
        - name: select
          in: body
          type: string
          description: Comma seperated fields to be displayed
        - name: sort
          in: body
          type: string
          description: sort parameter
        - name: skip
          in: body
          type: integer
          description: Number of records to skip
        - name: batchSize
          in: body
          type: integer
          description: Batch size for cursor
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - *ref_3
        - name: totalRecords
          in: query
          type: integer
          description: total records
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/fileTransfers:
    x-swagger-router-controller: controller
    get:
      description: Retrieve list of bulk actions'
      operationId: v1_srvc5443ExportDetails
      parameters:
        - name: page
          in: query
          type: integer
          description: Page number of the request
        - name: count
          in: query
          type: integer
          description: Number of records per page
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: filter
          in: query
          type: string
          description: Filter records based on certain fields
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: sort
          in: query
          type: string
          description: sort parameter
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/fileTransfers/count:
    x-swagger-router-controller: controller
    get:
      description: count of bulk actions'
      operationId: v1_srvc5443ExportDetailsCount
      parameters:
        - name: page
          in: query
          type: integer
          description: Page number of the request
        - name: count
          in: query
          type: integer
          description: Number of records per page
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: filter
          in: query
          type: string
          description: Filter records based on certain fields
        - name: select
          in: query
          type: string
          description: Comma seperated fields to be displayed
        - name: sort
          in: query
          type: string
          description: sort parameter
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  '/utils/fileTransfers/{id}':
    x-swagger-router-controller: controller
    delete:
      description: Deletes a file with file id
      operationId: v1_srvc5443ExportDetailsDelete
      parameters:
        - name: id
          in: path
          type: string
          required: true
          description: Id of file
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  '/utils/fileTransfers/{fileId}/readStatus':
    x-swagger-router-controller: controller
    put:
      description: Updates File Read Status
      operationId: exportUpdateReadStatus
      parameters:
        - name: fileId
          in: path
          type: string
          required: true
          description: Id of file
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: data
          in: body
          description: Payload with read status
          schema:
            properties:
              isRead:
                type: boolean
      responses:
        '200':
          description: File read status updated
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
  /utils/aggregate:
    x-swagger-router-controller: controller
    post:
      description: runs aggregate query
      operationId: v1_aggregate
      parameters:
        - name: authorization
          in: header
          type: string
          description: The JWT token for req.validation
        - name: data
          in: body
          description: Payload to aggregate
          schema:
            type: array
            items:
              type: object
      responses:
        '200':
          description: List of the entites
        '400':
          description: Bad parameters
        '500':
          description: Internal server error
definitions: {}
